### ISSUE TITLE
Changelog question

### ISSUE THREAD

**Issue by gunnx** [ellerbrock/node-npm-boilerplate#1]
I've been trying to write my own versions of commitizen conventions and conventional changelog.
I noticed you are using standard-version in this boilerplate, but from what I can see that is 'opinionated' and only uses angular convention. Though you are using a custom adapter for commitizen that uses angular emoji format.

**Comment by ellerbrock** [comment]
i wrote the angular emoji adapter myself: https://github.com/ellerbrock/conventional-changelog-angular-emoji
it uses emojis in the cli for a nicer interaction but keeps the commit messages like they are.
i hope this answers your question and sorry for the late replay.

cheers maik
